### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by LahanAR** [kashifpk/PyCK#50]
While in development it's very difficult to see the debugging messages for there is always rolling a message from route_permissions database requests.

I've tryed tweak the development.ini, but unsuccessful. The only way is to set the logger_sqlalchemy to WARN level.

On any pyramid regular scaffold it doesn't happened. Is there a way to tweak this?

Thank you.

**Comment by kashifpk** [comment]
Yes you can set the sqlalchemy log level to a higher value like WARN or
ERROR in development.ini

This will supress sqlalchemy related messages.
